---
- hosts: all
  become: True
  tasks:

  - name: Create directory for app
    file: path=/var/node/image_marker state=directory

  - name: checkout repo
    git: repo=git@github.com:vuza/image_marker.git dest=/var/node/image_marker force=yes accept_hostkey=True version=develop

  - name: install backend/npm dependencies
    npm: path=/var/node/image_marker

  - name: install frontend/bower dependencies
    bower: path=/var/node/image_marker relative_execpath=node_modules/.bin