---
- hosts: all
  vars_files:
    - vars/all.yml
  remote_user: "{{ remote_user }}"
  tasks:

  - name: Create directory for app
    become: True
    file: path={{ root }} state=directory owner={{ remote_user }} group=www-data

  - name: Create logging directory
    become: True
    file: path={{ loggingLocation }} state=directory owner={{ remote_user }}

  - name: checkout repo
    git: repo={{ git }} dest={{ root }} force=yes accept_hostkey=True version={{ gitVersion }}

  - name: install backend/npm dependencies
    npm: path={{ root }}

  - name: install im_processor
    npm: path={{ root }}/im_processor

  - name: install frontend/bower dependencies
    bower: path={{ root }}

  - name: Check list of Node.js apps running
    command: forever list
    register: forever_list
    changed_when: false

  - name: Start Node.js app
    command: forever start {{ root }}
    when: "forever_list.stdout.find('{{ root }}') == -1"