---
- hosts: all
  vars_files:
    - vars/all.yml
  tasks:

  - name: Create directory for app
    file: path={{ root }} state=directory

  - name: checkout repo
    git: repo={{ git }} dest={{ root }} force=yes accept_hostkey=True version=develop

  - name: install backend/npm dependencies
    npm: path={{ root }}

  - name: install im_processor
    npm: path={{ root }}

  - name: install frontend/bower dependencies
    bower: path={{ root }}

  - name: Check list of Node.js apps running
    command: forever list
    register: forever_list
    changed_when: false

  - name: Start Node.js app
    command: forever start {{ root }}
    when: "forever_list.stdout.find('{{ root }}') == -1"